export {default as AppBar } from './AppBar'
export {default as HomePage } from './HomePage'
export {default as Loader } from './Loader'
export {default as TopPage } from './TopPage'
export {default as Recommendations } from './Recommendations'
export {default as Random } from './Random'
export {default as Anime } from './Anime'
export {default as Schedules } from './Schedules/Schedules'